"""The real thing each object references, and what it looks like inside. Writes ai/remaster/prompts/<name>.txt and
<name>.inside.txt (overwriting the starting-point prompts; your AI and you can still edit them after).

    python3 ai/remaster/real_prompts.py
"""
import os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "prompts")

# name: the real product, described the way it was sold
REAL = {
    "console_64": "a 1996 Nintendo 64 console, charcoal grey, raised center with the cartridge slot, power and reset sliders, four controller ports on the front",
    "trident_controller": "a 1996 Nintendo 64 controller, grey three-pronged trident shape, center analog stick, blue A and green B buttons, four yellow C buttons, Z trigger underneath",
    "pocket_handheld": "a 1998 Nintendo Game Boy Color in translucent Grape purple, small color screen, d-pad, red A and B buttons",
    "wide_handheld": "a 2001 Nintendo Game Boy Advance in indigo, horizontal, screen in the middle, d-pad left, A and B right, shoulder buttons",
    "dual_screen_handheld": "a 2004 Nintendo DS, silver clamshell, two screens, stylus",
    "cube_console": "a 2001 Nintendo GameCube in indigo purple, cube with a carry handle on the back, round disc lid on top",
    "disc_console": "a 1995 Sony PlayStation, light grey, round disc lid, power and reset buttons, two controller ports",
    "twin_grip_controller": "a 1998 Sony PlayStation DualShock controller, grey, two analog sticks, triangle circle cross square buttons",
    "slim_tower_console": "a 2000 Sony PlayStation 2, black ribbed console standing vertical on its stand, blue PS logo",
    "big_x_console": "a 2001 Microsoft Xbox, huge black console with the big green jewel X on top",
    "giant_controller": "a 2001 original Xbox Duke controller, huge black controller with the green jewel in the center and colored face buttons",
    "swirl_console": "a 1999 Sega Dreamcast, white rounded console with the orange swirl logo",
    "vmu_controller": "a Sega Dreamcast controller, white, with a VMU memory card with a tiny LCD screen in its slot",
    "console_16bit": "a 1989 Sega Genesis, black console with 16-BIT printed on the round top",
    "monster_cart": "a 1998 Pokemon Red, Blue or Yellow Game Boy cartridge, colored label",
    "monster_card": "a 1999 Pokemon trading card, classic blue Poke Ball card back, holographic front",
    "monster_dex": "a 1998 red electronic Pokedex toy, flip-open",
    "duel_card": "a Yu-Gi-Oh! trading card, brown swirl card back",
    "battle_top": "a 2002 Beyblade spinning top, plastic and metal attack ring",
    "ripcord_launcher": "a Beyblade ripcord launcher with a toothed rip cord",
    "finger_skateboard": "a Tech Deck fingerboard with a printed deck graphic",
    "pog_slammer": "a 1994 metal POG slammer with a printed face",
    "pog_tube": "a clear POG tube full of printed cardboard POGs",
    "av_cable": "a red white and yellow composite AV cable with a console plug",
    "memory_card_stack": "a stack of PlayStation and GameCube memory cards",
    "game_case": "a PlayStation 2 game case open, disc hanging out",
    "strategy_guide": "a Prima Official Strategy Guide book from 1999",
    "console_box": "a 1996 Nintendo 64 retail box, printed cardboard",
    "rf_switch": "an RF switch box with antenna leads for a 1980s console",
    "light_gun": "a 1985 orange Nintendo Zapper light gun",
    "extension_cable": "a coiled grey controller extension cable",
    "gremlin": "a 1998 Furby, fuzzy owl-like talking toy with big eyes, eyelids, beak, ear tufts, tiger stripe fur",
    "gremlin_baby": "a 1999 Furby Baby, smaller, pastel fur",
    "gremlin_keychain": "a tiny Furby keychain",
    "gremlin_reboot": "a 2012 Furby with LCD screen eyes, bright fur",
    "gremlin_box": "a 1998 Furby sealed in its window retail box",
    "gremlin_dictionary": "the Furbish-English dictionary booklet that came with Furby",
    "gremlin_batteries": "a Duracell AA 4-pack next to a Furby battery door",
    "gremlin_sling": "a fabric Furby carry sling",
    "gremlin_stickers": "a Furby sticker sheet",
    "beanie_bear": "a 1997 Ty Beanie Baby bear with the red heart Ty tag in its ear",
    "beanie_dog": "a Ty Beanie Baby dog with the red heart Ty tag",
    "beanie_pig": "a Ty Beanie Baby pig with the red heart Ty tag",
    "beanie_lobster": "a Ty Beanie Baby lobster with the red heart Ty tag",
    "beanie_elephant": "Peanut the Ty Beanie Baby elephant with the red heart Ty tag",
    "beanie_frog": "a Ty Beanie Baby frog with the red heart Ty tag",
    "beanie_flamingo": "a Ty Beanie Baby flamingo with the red heart Ty tag",
    "beanie_tag_protector": "clear plastic Beanie Baby tag protectors",
    "beanie_price_guide": "a 1998 Beanie Baby price guide magazine",
    "beanie_display_case": "an acrylic Beanie Baby display case with a bear inside",
    "beanie_teeny": "a 1997 McDonald's Teenie Beanie Baby sealed in its bag",
    "beanie_certificate": "a limited edition Beanie Baby certificate of authenticity",
    "opera_saber": "a 1990s Star Wars collapsible toy lightsaber",
    "opera_carded": "a 1978 Kenner Star Wars action figure on its blister card back",
    "opera_figures": "loose 1980 Kenner Star Wars action figures",
    "opera_ship": "a 1979 Kenner Star Wars Millennium Falcon toy",
    "opera_mask": "a 1977 Darth Vader Halloween costume helmet",
    "opera_case": "a Kenner Star Wars vinyl figure carry case",
    "opera_lunchbox": "a 1977 Star Wars metal lunchbox",
    "opera_vhs": "the Star Wars Trilogy VHS box set, 1995",
    "opera_cards": "1977 Topps Star Wars trading cards",
    "opera_stickers": "a Star Wars sticker sheet",
    "opera_mailaway": "a Kenner Star Wars mail-away Boba Fett offer and figure",
    "trip_it": "a 1990s Skip-It ankle toy with the counter ball",
    "flop_it": "a 1996 Bop It, purple green and yellow",
    "kush_ball": "a Koosh ball, rubber filaments",
    "moon_shooz": "Nerf Moon Shoes mini trampolines for your feet",
    "blow_up_gloves": "Sock'em Boppers inflatable boxing gloves",
    "soggy_blaster": "a Super Soaker 50 water gun, neon green and orange",
    "nerd_blaster": "a Nerf foam dart blaster with darts",
    "stretch_man": "a Stretch Armstrong figure",
    "wrestler_fig": "a 1990s WWF wrestling action figure",
    "micro_cars": "Micro Machines tiny cars",
    "loop_track": "an orange Hot Wheels track with a loop",
    "robo_car": "a 1984 Transformers robot car toy",
    "pocket_playset": "a pink Polly Pocket compact playset",
    "monster_playset": "a Mighty Max skull playset",
    "bug_oven": "a Creepy Crawlers Thingmaker oven with molds",
    "toy_oven": "a 1990s purple and pink Easy-Bake Oven",
    "tickle_monster": "a 1996 Tickle Me Elmo plush",
    "stereo_viewer": "a red View-Master viewer with a picture reel",
    "yapper_boy": "a Talkboy cassette recorder from Home Alone 2, silver with the big mic",
    "yak_toy": "a Yak Bak handheld voice recorder toy",
    "clip_player": "a Hasbro HitClips player with song cartridges",
    "eye_pod": "a 2004 white Apple iPod Classic with the click wheel",
    "mini_pod": "a 2004 Apple iPod Mini in colored aluminum",
    "nano_pod": "a 2005 Apple iPod Nano, glossy",
    "razor_phone": "a 2004 Motorola Razr V3 flip phone, silver",
    "snake_phone": "a Nokia 3310 brick phone with Snake on the screen",
    "sidekick_phone": "a T-Mobile Sidekick with the swivel screen",
    "crackberry": "a BlackBerry with a tiny keyboard",
    "pda": "a Palm Pilot PDA with stylus",
    "instant_camera": "a Polaroid 600 instant camera",
    "instant_photos": "Polaroid instant photo prints",
    "fruit_computer": "a 1998 Bondi Blue Apple iMac G3, translucent",
    "cow_box": "a Gateway computer box with the cow print",
    "beige_tower": "a 1990s beige Dell Dimension tower PC",
    "cdr_spindle": "a 50-pack spindle of blank CD-Rs",
    "os_box": "a boxed copy of Windows 95",
    "trial_cd": "an AOL free trial CD, 1000 hours free",
    "trial_tin": "an AOL free trial CD in its metal tin",
    "modem_56k": "a 56K external US Robotics modem with status lights",
    "beige_keyboard": "a beige IBM Model M style keyboard",
    "ball_mouse": "a beige ball mouse, ball popping out",
    "phone_cord": "a coiled beige RJ11 phone line cord",
    "mousepad": "a 1990s mousepad with the flying toasters screensaver",
    "im_stickers": "an AOL Instant Messenger running man sticker sheet",
    "p2p_sleeve": "a CD sleeve with the Napster and LimeWire logos, burned music",
    "skin_printout": "a printout of a Winamp skin",
    "hours_mailer": "an AOL 1000 Hours Free mailer envelope",
    "cdr_sharpie": "a burned CD-R labeled in Sharpie",
    "rental_vhs": "a blue and yellow Blockbuster Video rental VHS case",
    "new_release_case": "a Blockbuster New Release case with the sticker",
    "rental_game": "a Blockbuster video game rental case",
    "rental_card": "a Blockbuster Video membership card",
    "latefee_receipt": "a Blockbuster late fee receipt",
    "car_rewinder": "a car-shaped VHS rewinder",
    "popcorn_bag": "an Orville Redenbacher microwave popcorn bag",
    "theater_candy": "a box of Milk Duds theater candy",
    "dvd_case": "an early 2000s DVD keep case",
    "dropbox_door": "the return slot door of a Blockbuster drop box",
    "bkr_sticker": "a Be Kind Please Rewind sticker",
    "speaker_6x9": "a Pioneer 6x9 oval car speaker",
    "subwoofer": "a 12 inch Kicker subwoofer",
    "car_amp": "a 1990s Rockford Fosgate amplifier with airbrushed graphics and heat sink fins",
    "head_unit": "a 1990s Alpine car stereo with a removable faceplate and blue display",
    "faceplate_case": "a hard case for a car stereo faceplate",
    "rca_cables": "twisted RCA car audio cables",
    "stiff_cap": "a car audio stiffening capacitor with a blue voltage display",
    "underglow": "a neon underglow tube for a car",
    "bass_knob": "a remote bass knob",
    "cd_changer": "a trunk-mounted 10-disc CD changer",
    "cassette_adapter": "a cassette tape adapter with a cord for a Discman",
    "tweeter": "a swivel car audio tweeter",
    "amp_kit": "a car amplifier wiring kit",
    "audio_stickers": "car audio brand stickers: Kicker, Rockford Fosgate, Alpine, JL Audio",
    "trapped_keeper": "a 1988 Mead Trapper Keeper with loud graphics",
    "neon_folder": "a Lisa Frank folder with neon dolphins and a unicorn",
    "five_subject": "a Mead Five Star notebook",
    "backpack": "a JanSport backpack",
    "gel_pens": "Gelly Roll glitter gel pens",
    "scented_markers": "Mr. Sketch scented markers",
    "crayon_box": "a Crayola 64 box with the built-in sharpener",
    "tin_lunchbox": "a metal cartoon lunchbox with a matching thermos",
    "plastic_lunchbox": "a 1990s plastic lunch box",
    "launchables": "an Oscar Mayer Lunchables cracker stacker tray",
    "drink_pouch": "a Capri Sun silver pouch with the straw",
    "orange_jug": "a Sunny D orange drink jug",
    "mini_barrels": "Little Hug Fruit Barrels twist-top drinks",
    "squeeze_buddy": "a Squeezit character drink bottle",
    "frosting_dip": "Dunkaroos cookies and frosting tray",
    "gusher_box": "a Fruit Gushers box and pouch",
    "fruit_strip": "Fruit by the Foot rolled fruit strip",
    "ring_candy": "a Ring Pop",
    "push_pop": "a Push Pop",
    "sour_pack": "a Warheads sour candy pack",
    "baby_bottle_pop": "a Baby Bottle Pop",
    "wonder_ball": "a Nestle Wonder Ball in foil",
    "orb_bottle": "an Orbitz drink bottle with floating balls",
    "crystal_cola": "a 1992 Crystal Pepsi bottle",
    "chip_bag_3d": "a bag of Doritos 3D",
    "splurge_can": "a 1997 Surge soda can, lime green",
    "pizza_box": "a Pizza Hut personal pan pizza box with a Book It! button",
    "lunch_tray": "a plastic school cafeteria tray",
    "school_milk": "a school chocolate milk carton",
    "card_toploader": "a 1989 Upper Deck Ken Griffey Jr. rookie card in a top-loader",
    "wax_pack": "a 1990 Topps baseball wax pack with gum",
    "signed_baseball": "a signed baseball in a cube case",
    "foam_finger": "a #1 foam finger",
    "felt_pennant": "a felt team pennant",
    "bobblehead": "a stadium giveaway bobblehead",
    "jersey_scrap": "a torn 1990s replica jersey",
    "snapback_cap": "a 1990s Starter snapback cap",
    "ticket_stubs": "1990s Ticketmaster ticket stubs",
    "mini_helmet": "a Riddell mini football helmet",
    "card_binder_sheet": "a 9-pocket binder page of baseball cards",
    "satin_jacket": "a Starter satin team jacket",
    "slime_tub": "Nickelodeon Gak in its tub, green",
    "splat_sign": "the orange Nickelodeon splat logo sign",
    "putty_egg": "Nickelodeon Floam / Gak putty egg",
    "foam_bead_tub": "a tub of Nickelodeon Floam",
    "orange_vhs": "an orange Nickelodeon clamshell VHS",
    "dare_flag": "a Double Dare obstacle course flag",
    "slime_cereal": "a 1990s cartoon tie-in cereal box",
    "bubble_tape": "Hubba Bubba Bubble Tape",
    "slime_stickers": "a 1990s gross-out sticker sheet",
    "kid_blimp": "the Nickelodeon Kids' Choice blimp toy",
    "chews_trophy": "a Nickelodeon Kids' Choice Awards orange blimp trophy",
    "walkman": "a 1985 Sony Walkman cassette player",
    "portable_cd": "a 1995 Sony Discman portable CD player",
    "game_cart": "a 1988 Nintendo NES game cartridge, grey",
    "controller_16bit": "a 1991 Super Nintendo controller",
    "virtual_pet": "a 1997 Tamagotchi egg-shaped virtual pet",
    "brick_game": "a 9999-in-1 Brick Game handheld",
    "milk_caps": "1993 POG milk caps",
    "boombox": "a 1980s JVC boombox",
    "candybar_phone": "a 1999 Nokia candybar phone",
    "flip_phone": "a 2000s flip phone",
    "pager": "a 1990s Motorola pager",
    "handheld": "a Nintendo Switch handheld",
    "mp3_player": "an early 2000s MP3 player",
    "energy_can": "a Red Bull energy drink can",
    "soda_can": "a soda can of the era",
    "beer_can": "a beer can of the era",
    "crt": "a beige CRT computer monitor",
    "floppy": "a 3.5 inch floppy disk",
    "vhs": "a black VHS tape with a handwritten label",
    "cassette": "a cassette tape with a handwritten label",
    "cd": "a burned CD",
    "magazine": "a 1990s Playboy magazine",
    "centerfold": "a Playboy centerfold",
    "puzzle_cube": "a Rubik's Cube",
    "slap_bracelet": "a slap bracelet",
    "skateboard": "a 1990s skateboard",
    "sneaker": "a Nike Air Jordan sneaker",
    "smartphone": "an iPhone",
    "tablet": "an iPad",
}

# what each kind of thing looks like inside when it splits open
INSIDE = [
    (("console", "controller", "handheld", "cart", "dex", "phone", "pod", "player", "pda", "modem", "keyboard",
      "mouse", "tower", "computer", "camera", "amp", "head_unit", "cd_changer", "stiff_cap", "rf_switch", "light_gun",
      "yak", "yapper", "clip", "pager", "crackberry", "walkman", "portable_cd", "boombox", "brick_game",
      "virtual_pet", "crt", "tablet", "remote", "calculator", "gremlin_reboot", "tickle"),
     "a green circuit board with black chips, gold contacts and solder points, small wires, a speaker or battery"),
    (("gremlin", "beanie", "plush", "kush", "tickle", "moon_shooz"),
     "white polyester stuffing and tiny plastic pellets, inside seams, a little plastic motor box for the talking ones"),
    (("candy", "choc", "bar", "wonder_ball", "ring_candy", "push_pop", "sour", "bottle_pop", "gusher", "fruit",
      "frosting", "launchables", "bubble", "theater", "marshmallow"),
     "the food inside: chocolate, caramel, nougat, wafer layers, sugar crystals, gooey fruit filling"),
    (("can", "barrels", "jug", "bottle", "cola", "orb", "pouch", "milk", "drink"),
     "bare aluminum or thin plastic walls, a little sticky soda or juice, foil lining"),
    (("vhs", "cassette", "tape", "rental"), "black magnetic tape on white plastic reels, tiny screws, the felt pad"),
    (("cd", "trial", "dvd", "disc"), "shattered polycarbonate with a rainbow sheen and a silver foil layer"),
    (("card", "pog", "sticker", "receipt", "guide", "magazine", "centerfold", "dictionary", "certificate", "mailer",
      "printout", "folder", "notebook", "keeper", "box", "sleeve", "ticket", "pennant", "mousepad", "newspaper"),
     "layers of printed paper and cardboard, torn fibers, glossy coating peeling off"),
    (("speaker", "subwoofer", "tweeter"), "a copper voice coil, a heavy round magnet, paper cone, spider fabric"),
    (("sneaker", "shoe", "skate"), "foam midsole, fabric lining, glue and stitching"),
    (("slime", "putty", "floam", "foam_bead", "gak"), "squishy green slime with foam beads stuck in it"),
]
DEFAULT_INSIDE = "the raw material inside: hollow plastic shell with molded ribs and screw posts, scratched and cracked"


def inside_for(name):
    for keys, text in INSIDE:
        if any(k in name for k in keys):
            return text
    return DEFAULT_INSIDE


def main():
    names = sorted(p[:-4] for p in os.listdir(OUT) if p.endswith(".txt") and not p.endswith(".inside.txt"))
    for n in names:
        if n in REAL:
            open(os.path.join(OUT, n + ".txt"), "w").write(REAL[n] + ", worn from use, true colors and materials.\n")
        p = os.path.join(OUT, n + ".inside.txt")
        if not os.path.exists(p):
            open(p, "w").write(inside_for(n) + ".\n")
    print(f"{sum(n in REAL for n in names)} real-product prompts, {len(names)} inside prompts -> {OUT}")


if __name__ == "__main__":
    main()
