"""Nostalgia: the world's childhood crazes, mostly 1985-2008. Eight one-of-ones and the real things they parody."""

ONES = {
    "SURPRISE INSIDE": {
        "mix": [("surprise_egg", 14), ("surprise_capsule", 8), ("surprise_toy", 8), ("surprise_slip", 5),
                ("choc_egg_shell", 5), ("hazelnut_wafer_bar", 3), ("joy_egg", 4), ("kids_choc_bar", 5),
                ("crumpled_paper", 2), ("gum_wrapper", 2)],
        "lore": "Contraband under American law: forty chocolate eggs with a toy inside, smuggled home in a suitcase "
                "and opened on the kitchen floor.",
        "flavor": ("Cheap Milk Chocolate and Foil", "A Suitcase, Back From Vacation", "Kinda Surprise Egg"),
        "era": {0, 1, 2, 3},
        "fillers": ("choc_egg_shell", "surprise_slip", "surprise_capsule", "gum_wrapper"),
        "soft": 0.5,
        "no_wires": True,
    },
    "GOT GOT NEED": {
        "mix": [("sticker_album", 3), ("sticker_packet", 10), ("football_sticker", 16), ("shiny_badge", 5),
                ("swap_stack", 4), ("flick_figure", 5), ("foam_football", 1), ("jersey_scrap", 2), ("mini_flag", 3),
                ("crumpled_paper", 2)],
        "lore": "Italia 90 to France 98 in one swap pile: the album half full, the doubles rubber-banded, the shiny "
                "never found.",
        "flavor": ("Sticker Glue and Playground Asphalt", "A Pencil Case, Back Row", "Panetti Sticker Album"),
        "era": {0, 1, 2},
        "fillers": ("football_sticker", "sticker_packet", "football_sticker", "crumpled_paper"),
        "soft": 0.45,
        "no_wires": True,
    },
    "PICK 'N' MIX": {
        "mix": [("pick_bag", 4), ("candy_scoop", 1), ("cola_bottles", 7), ("foam_shrimps", 6), ("fried_eggs", 6),
                ("white_mice", 5), ("flying_saucers", 6), ("fizzy_laces", 6), ("jelly_babies", 7), ("chew_bar", 4)],
        "lore": "One paper bag every Saturday, filled by weight and gone by Monday, from a high-street store that is "
                "not there anymore.",
        "flavor": ("Sugar Dust and Paper Bag", "The High Street, Saturday Morning", "Pick 'n' Mix Bag"),
        "era": {0, 1, 2},
        "fillers": ("flying_saucers", "jelly_babies", "fizzy_laces", "cola_bottles"),
        "soft": 0.5,
        "no_wires": True,
    },
    "GACHAPON": {
        "mix": [("gacha_capsule", 12), ("gacha_figure", 8), ("menko_card", 5), ("seal_sticker", 5),
                ("pocket_diecast", 3), ("famicom_cart", 2), ("umaibo", 6), ("calpis_bottle", 2), ("kinkeshi", 7),
                ("gacha_knob", 1)],
        "lore": "Two hundred yen at a time outside a Tokyo toy shop: a wall of capsules, the toy nobody wanted, and a "
                "crank that clicks.",
        "flavor": ("Corn Puff and Capsule Plastic", "Outside a Toy Shop, Tokyo", "Capsule Machine Crank"),
        "era": {0, 1, 2},
        "fillers": ("gacha_capsule", "kinkeshi", "seal_sticker", "umaibo"),
        "soft": 0.5,
        "no_wires": True,
    },
    "PURIKURA": {
        "mix": [("purikura_sheet", 10), ("charm_phone", 3), ("keitai_strap", 6), ("virtual_pet", 3),
                ("stick_biscuit_box", 5), ("fruit_chew", 7), ("loose_socks", 3), ("gel_pens", 5), ("magic_wand", 2),
                ("gb_pocket", 2)],
        "lore": "A Shibuya schoolbag, emptied: a planner full of photo stickers, a phone wearing its weight in charms, "
                "and one loose sock.",
        "flavor": ("Strawberry Chew and Hairspray", "A Schoolbag, Shibuya, 1999", "Decorated Flip Phone"),
        "era": {2, 3},
        "fillers": ("purikura_sheet", "keitai_strap", "fruit_chew"),
        "soft": 0.5,
        "no_wires": True,
    },
    "TAZOS": {
        "mix": [("tazo", 18), ("tazo_chip_bag", 6), ("tazo_tube", 3), ("puff_bag", 4), ("tazo_board", 2),
                ("pog_slammer", 4), ("glass_soda", 3), ("milk_caps", 3), ("bottle_cap", 4), ("crumpled_paper", 2)],
        "lore": "Bought for the disc, not the chips: a year of recess from Madrid to Monterrey to Buenos Aires, "
                "slammed flat on the patio.",
        "flavor": ("Chili Lime Dust and Orange Fingers", "A Schoolyard Patio, Recess", "Taza Collector Tube"),
        "era": {1, 2},
        "fillers": ("tazo", "tazo", "bottle_cap", "crumpled_paper"),
        "soft": 0.5,
        "no_wires": True,
    },
    "SPAM GIFT SET": {
        "mix": [("spam_gift_box", 2), ("spam_can", 10), ("gift_oil_bottle", 3), ("songpyeon", 8), ("persimmon", 5),
                ("asian_pear", 3), ("hwatu_cards", 6), ("yut_sticks", 3), ("choco_pie_box", 6), ("banana_milk", 5)],
        "lore": "Chuseok, the harvest holiday, when canned ham is the gift you give your boss: eight tins in a box "
                "with a handle and a bottle of oil.",
        "flavor": ("Fried Ham and Sesame Oil", "Grandmother's Apartment, Chuseok", "Splam Gift Set"),
        "era": {1, 2, 3},
        "fillers": ("songpyeon", "hwatu_cards", "crumpled_paper"),
        "soft": 0.6,
        "no_wires": True,
    },
    "GOLAZO": {
        "mix": [("tango_football", 2), ("team_scarf", 4), ("vuvuzela", 3), ("air_horn", 3), ("mascot_plush", 2),
                ("flag_bunting", 4), ("wallchart", 2), ("foam_finger", 3), ("soda_can", 8), ("jersey_scrap", 4),
                ("mini_flag", 6), ("football_sticker", 5), ("party_cup", 2)],
        "lore": "Every four years the whole planet stops work: scarves in June, horns at dawn, a wallchart filled in "
                "until your team went out.",
        "flavor": ("Spilled Beer and Plastic Horn", "The Bar at Kickoff, Every Four Years", "Match Ball"),
        "era": {1, 2, 3, 4},
        "fillers": ("mini_flag", "football_sticker", "party_cup", "crumpled_paper"),
        "soft": 0.6,
        "no_wires": True,
    },
}

_S = "single object, plain background, product photo"

REAL = {
    # SURPRISE INSIDE
    "surprise_egg": f"a Kinder Surprise chocolate egg from the 1990s in its white foil printed with the orange and red Kinder logo, or opened: two milk-chocolate shell halves with white lining and the yellow plastic toy capsule, {_S}",
    "surprise_capsule": f"the yellow plastic two-part capsule from inside a Kinder Surprise egg, rounded pill shape, one half sleeved over the other, {_S}",
    "surprise_toy": f"a small Kinder Surprise toy from the 1990s: a tiny painted plastic figure or a four-piece snap-together car with a decal, or unassembled parts on a plastic sprue, {_S}",
    "surprise_slip": f"a small accordion-folded paper instruction slip from a Kinder Surprise toy, line drawings of numbered assembly steps and a 0-3 age warning symbol, {_S}",
    "choc_egg_shell": f"broken pieces of a hollow milk chocolate egg shell, brown outside with a white milk-cream lining, {_S}",
    "hazelnut_wafer_bar": f"a Kinder Bueno bar from the 1990s, white wrapper with orange and brown print, or the bumpy chocolate-drizzled hazelnut wafer bar unwrapped, {_S}",
    "joy_egg": f"a Kinder Joy egg from the 2000s in its orange and white foil, or opened: the plastic egg split into a cream half with two wafer balls and a toy half with the capsule, with the small plastic spoon, {_S}",
    "kids_choc_bar": f"a single Kinder Chocolate bar, white wrapper with the red Kinder logo and a glass of milk printed on it, or the milk chocolate bar with the white milky center, {_S}",
    # GOT GOT NEED
    "football_sticker": f"a single Panini World Cup football sticker from Italia 90 or USA 94, a player head-and-shoulders photo with name bar and flag, glossy paper backing, {_S}",
    "sticker_packet": f"a Panini World Cup sticker packet from the 1990s, foil-paper wrapper with the tournament logo and the Panini knight logo, torn open with stickers showing, {_S}",
    "sticker_album": f"a Panini World Cup sticker album from 1990 to 1998, glossy cover with the tournament logo, opened on a half-filled page of player stickers and empty numbered spaces, {_S}",
    "shiny_badge": f"a shiny foil Panini team badge sticker, a national team crest on silver-gold holographic foil, {_S}",
    "swap_stack": f"a thick stack of duplicate Panini football stickers held together with a rubber band, worn rounded corners, {_S}",
    "flick_figure": f"a Subbuteo table football player figure from the 1980s, a tiny hand-painted player on a hemispherical weighted base with a colored ring, {_S}",
    "foam_football": f"a soft foam indoor football with printed pentagon panels, slightly squashed, {_S}",
    # PICK 'N' MIX
    "pick_bag": f"a Woolworths Pick 'n' Mix paper candy bag from the 1990s, white with colored candy stripes and the Woolworths name, top twisted shut, sugar grease spots, {_S}",
    "candy_scoop": f"a clear plastic candy scoop from a pick 'n' mix sweet counter, {_S}",
    "cola_bottles": f"a few gummy cola bottles from a pick 'n' mix counter, brown at the bottom shading to clear at the top, some sugar-coated fizzy ones, {_S}",
    "foam_shrimps": f"a few pink and white foam shrimp sweets from a pick 'n' mix counter, curled, chalky foam texture, {_S}",
    "fried_eggs": f"a few gummy fried egg sweets from a pick 'n' mix counter, white foam base with a glossy yellow gummy yolk, {_S}",
    "white_mice": f"a few chalky white and pink sugar mice sweets with string-like tails, {_S}",
    "flying_saucers": f"a few flying saucer sweets, pastel-colored rice paper discs filled with sherbet, {_S}",
    "fizzy_laces": f"a tangle of sugar-coated sour fizzy laces in red, green, blue and orange, {_S}",
    "jelly_babies": f"a few Bassett's Jelly Babies in red, orange, yellow, green, black and pink, floury matte finish, {_S}",
    "chew_bar": f"a Wham fizzy chew bar from the 1980s, pink and blue wrapper with the yellow lightning Wham logo, {_S}",
    # GACHAPON
    "gacha_capsule": f"a Japanese gashapon capsule, clear plastic top and colored bottom half, a tiny toy and a folded paper slip inside, {_S}",
    "gacha_figure": f"a small painted Japanese gashapon figure from the 1990s, a tiny robot, cat or dinosaur in PVC, {_S}",
    "menko_card": f"a round Japanese menko card from the 1980s, thick printed cardboard with a superhero illustration and a number, bent from play, {_S}",
    "seal_sticker": f"a Bikkuriman holographic seal sticker from a Lotte chocolate wafer, 1980s, shiny prism foil with an angel or devil character, {_S}",
    "pocket_diecast": f"a Tomica 1/64 die-cast car from the 1990s, a Japanese sedan, police car or taxi, sometimes with its small red and white Tomica box, {_S}",
    "famicom_cart": f"a Nintendo Famicom cartridge from the 1980s, short wide candy-colored plastic shell with grip ridges on the sides and an illustrated label, {_S}",
    "umaibo": f"an Umaibo corn puff stick, ten-yen Japanese snack in a printed plastic wrapper, corn potage or mentai flavor, hollow puff tube, {_S}",
    "calpis_bottle": f"a Calpis Water plastic bottle from the 1990s, white with blue polka dots, blue cap, {_S}",
    "kinkeshi": f"a Kinnikuman kinkeshi rubber eraser figure from the 1980s, one-color pink or orange rubber muscle wrestler, {_S}",
    "gacha_knob": f"the front plate of a Japanese gashapon capsule machine, coin slot, chrome crank dial with a colored handle, price printed in yen, {_S}",
    # PURIKURA
    "purikura_sheet": f"a sheet of Japanese purikura photo-booth stickers from the late 1990s, a grid of small frames with two teenage friends making peace signs, decorated with hearts, stars and handwriting, some peeled off, {_S}",
    "charm_phone": f"a Japanese clamshell flip phone from the early 2000s decorated with rhinestones and covered in dangling phone straps, charms, beads and a bell, {_S}",
    "keitai_strap": f"a bunch of Japanese phone straps from the early 2000s, cords with beads, a little bell, a plastic star, a fluffy pompom and a tiny bear charm, {_S}",
    "stick_biscuit_box": f"a box of Pocky chocolate biscuit sticks, red box with a few chocolate-dipped sticks sliding out, {_S}",
    "fruit_chew": f"a Morinaga Hi-Chew stick pack from the 2000s, strawberry or grape, or a few individually wrapped chews, {_S}",
    "loose_socks": f"a single white Japanese loose sock from the late 1990s, very long and baggy, bunched in rings, {_S}",
    "magic_wand": f"a 1990s toy magical girl wand, pink plastic stick with a gold star head, a heart jewel, small white wings and ribbons, {_S}",
    "gb_pocket": f"a 1996 Nintendo Game Boy Pocket, slim handheld, gray-green screen, d-pad, A and B buttons, in silver, gold, red or pink, {_S}",
    # TAZOS
    "tazo": f"a Tazos plastic disc from Matutano or Sabritas chips in the late 1990s, round printed cartoon disc with a number, some shiny, {_S}",
    "tazo_chip_bag": f"a Sabritas or Matutano potato chip bag from the late 1990s with a burst advertising free Tazos inside, {_S}",
    "tazo_tube": f"a clear plastic Tazos collector tube with a colored cap, packed with plastic discs, {_S}",
    "puff_bag": f"a bag of Cheetos or Chizitos cheese puffs from the late 1990s, orange bag with puffs spilling out, {_S}",
    "tazo_board": f"a cardboard Tazos collector board with round holes for each disc, some discs pushed in, {_S}",
    "glass_soda": f"a Jarritos glass soda bottle, tall clear glass with ribbed neck, mandarin, tamarind or lime soda, colorful printed label, crown cap, {_S}",
    # SPAM GIFT SET
    "spam_can": f"a CJ Spam can from Korea, rounded rectangular tin with pull-ring lid, blue and yellow label with a slice of ham, {_S}",
    "spam_gift_box": f"a Korean Chuseok CJ Spam gift set, navy blue and gold box with a plastic carry handle, lid open on rows of Spam cans in a tray, {_S}",
    "gift_oil_bottle": f"a Korean holiday gift set canola oil bottle, Beksul brand, clear PET bottle of yellow oil with a green and yellow label, {_S}",
    "songpyeon": f"several Korean songpyeon rice cakes, half-moon shapes in white, pink, green and yellow, on pine needles, {_S}",
    "persimmon": f"a ripe Korean persimmon, glossy orange, squat with a four-leaf green-brown calyx, {_S}",
    "asian_pear": f"a large Korean Asian pear, round golden-brown freckled skin, in a white foam net sleeve, {_S}",
    "hwatu_cards": f"a few Korean hwatu flower cards, small thick cards with red backs and faces showing pine and crane, cherry blossom, moon over a black hill, {_S}",
    "yut_sticks": f"four wooden yut nori sticks, half-round, flat face up or down, one marked with an X, {_S}",
    "choco_pie_box": f"an Orion Choco Pie box from Korea, red box with the heart symbol, or a single Choco Pie in its red wrapper, or a chocolate-coated marshmallow cake with a bite out, {_S}",
    "banana_milk": f"a Binggrae banana flavored milk bottle, squat pale yellow jug-shaped plastic bottle with a foil peel top and green lettering, {_S}",
    # GOLAZO
    "tango_football": f"an Adidas Tango or Etrusco Unico football from the 1980s or 1990 World Cup, white with black triad circles, scuffed, {_S}",
    "team_scarf": f"a knitted football supporters bar scarf with a team chant in block letters, two colors, tassels on both ends, folded, {_S}",
    "vuvuzela": f"a plastic vuvuzela stadium horn from the 2010 World Cup in South Africa, long cone, bright yellow or flag-striped, {_S}",
    "air_horn": f"a handheld aerosol air horn, metal canister with a printed label and a red plastic trumpet on top, {_S}",
    "mascot_plush": f"a small plush football mascot toy, a cartoon frog in a jersey holding a ball, claw machine quality, {_S}",
    "flag_bunting": f"a string of small paper national flags bunting for the World Cup, {_S}",
    "wallchart": f"a newspaper World Cup wallchart from the 1990s, folded, group tables and knockout bracket partly filled in with pen, {_S}",
}

INSIDE = {
    "surprise_egg": "a thin milk chocolate shell with a white milk lining, and the yellow plastic toy capsule",
    "surprise_capsule": "the tiny plastic toy parts and a folded paper slip",
    "surprise_toy": "solid painted plastic",
    "surprise_slip": "folded paper",
    "choc_egg_shell": "milk chocolate and white milk cream",
    "hazelnut_wafer_bar": "crisp wafer filled with hazelnut cream under milk chocolate",
    "joy_egg": "milky cocoa cream, two wafer balls and a yellow toy capsule",
    "kids_choc_bar": "milk chocolate around a white milky filling",
    "football_sticker": "paper and adhesive backing",
    "sticker_packet": "five stickers in a stack",
    "sticker_album": "glossy paper pages, stickers stuck in and empty numbered boxes",
    "shiny_badge": "foil paper and adhesive backing",
    "swap_stack": "dozens of stickers in a stack",
    "flick_figure": "solid painted plastic and a lead weight in the base",
    "foam_football": "soft yellow open-cell foam",
    "pick_bag": "a jumble of gummy and foam sweets in sugar dust",
    "candy_scoop": "solid plastic",
    "cola_bottles": "translucent brown gummy",
    "foam_shrimps": "pink and white marshmallow foam",
    "fried_eggs": "white marshmallow foam and yellow gummy",
    "white_mice": "chalky white sugar",
    "flying_saucers": "rice paper and powdery sherbet",
    "fizzy_laces": "chewy gummy with sour sugar",
    "jelly_babies": "soft translucent gummy",
    "chew_bar": "pink chew with fizzy sherbet bits",
    "gacha_capsule": "a tiny painted figure and a folded paper slip",
    "gacha_figure": "solid PVC plastic",
    "menko_card": "layers of gray cardboard",
    "seal_sticker": "foil and adhesive backing",
    "pocket_diecast": "zinc die-cast metal, a plastic interior and axles",
    "famicom_cart": "a green circuit board with black chips and gold contacts",
    "umaibo": "a hollow crunchy corn puff tube with seasoning dust",
    "calpis_bottle": "milky white drink",
    "kinkeshi": "solid rubber",
    "gacha_knob": "gears, a spring and coins",
    "purikura_sheet": "glossy photo paper and adhesive backing",
    "charm_phone": "a green circuit board with black chips, a battery and a tiny speaker",
    "keitai_strap": "cords, beads and solid plastic charms",
    "stick_biscuit_box": "two foil bags of chocolate-dipped biscuit sticks",
    "fruit_chew": "soft fruit chew in wax paper",
    "loose_socks": "thick white knit cotton",
    "magic_wand": "a hollow plastic stick, AA batteries and a little light bulb",
    "gb_pocket": "a green circuit board with black chips, AAA batteries and a speaker",
    "tazo": "solid plastic",
    "tazo_chip_bag": "potato chips and a plastic disc in a little bag",
    "tazo_tube": "a stack of plastic discs",
    "puff_bag": "orange cheese puffs and orange dust",
    "tazo_board": "gray cardboard",
    "glass_soda": "bright fruit soda and fizz",
    "spam_can": "pink pressed ham in clear jelly",
    "spam_gift_box": "gray cardboard, a molded plastic tray and tins",
    "gift_oil_bottle": "golden cooking oil",
    "songpyeon": "chewy rice dough around sesame seeds and honey or sweet beans",
    "persimmon": "soft orange flesh",
    "asian_pear": "crisp white juicy flesh",
    "hwatu_cards": "thick red plastic",
    "yut_sticks": "pale wood",
    "choco_pie_box": "soft cake, white marshmallow and a chocolate coating",
    "banana_milk": "pale yellow banana milk",
    "tango_football": "a black rubber bladder and fabric lining",
    "team_scarf": "thick knit acrylic",
    "vuvuzela": "hollow plastic",
    "air_horn": "a metal can and a valve",
    "mascot_plush": "white polyester stuffing",
    "flag_bunting": "paper and string",
    "wallchart": "folded newsprint",
}
